### ISSUE TITLE
Cash App Pay Button

### ISSUE THREAD

**Issue by shivang1411** [square/web-sdk#108]
I am getting issue while I am re-generating Cash App button and destroy not working as expected   
![image](https://user-images.githubusercontent.com/107907690/176194844-d583cf4b-c433-437c-bec1-73014effbe66.png)

**Comment by maorleger** [comment]
Hi @shivang1411 - thank you for opening this issue and allowing us to help! 

You're quite right that destroy is not fully implemented but we are releasing an update for this which should provide full `destroy` functionality. I'll reach out with another update when that is released (sometime this week)

**Comment by maorleger** [comment]
Hi @shivang1411 - we just rolled out a change to square.js that should resolve this and fully implement destroy. Could you give this a try and let us know if you continue running into issues?

**Comment by shivang1411** [comment]
Thank you for your quick support on this, I test this and It's working fine, If I'll face any issue will contact you 
Thank you again..
