### ISSUE TITLE
Cash Pay Button In Angular

### ISSUE THREAD

**Issue by shivang1411** [square/web-sdk#109]
**Describe the bug**
Once Cash App pay button payment done and try to regenerate button again for another payment that gave previous success button details 
that happen in Angular 10.0.7 

**To Reproduce**

1. Open Cash App QR
2. Payment done
3. Try New Payment
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/107907690/176890284-7ccf80a6-aa92-432a-81ea-b40dd5c889be.png)

**Comment by shivang1411** [comment]
Is there any update on this issue ?

**Comment by maorleger** [comment]
Hi @shivang1411 - thanks for your patience as we were looking into this. Unfortunately Pay Kit does not support this usecase today (creating another payment). A workaround might involve reloading the page after the payment is complete. 

If this is a scenario you're interested in seeing support for, [let us know!](https://www.sellercommunity.com/t5/Feature-Requests/ct-p/Beta-Feature-Requests)

**Comment by shivang1411** [comment]
Hello @maorleger 
Thank you for your replay,
I have product list and using angular so there is no reload scenario, is there any other way for this to make it work ?

**Comment by maorleger** [comment]
Hey @shivang1411 - I am happy to share that we have implemented support for restarting Cash App Pay. You will want to `destroy` the current instance and re-initialize (and attach) in order to support your scenario. Hope this helps!

**Comment by maxbeatty** [comment]
Here's an example using vanilla JavaScript to create many payments using Cash App Pay on a single page

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Square Web Payments SDK - Cash App Pay - Multiple payments</title>
    <meta charset="UTF-8" />
  </head>

  <body>
    <div id="cash-app-pay"></div>

    <script src="https://sandbox.web.squarecdn.com/v1/square.js"></script>
    <script src="src/index.js"></script>
  </body>
</html>
```

```js
const appId = "YOUR_SANDBOX_APPLICATION_ID";
const locationId = "YOUR_SANDBOX_LOCATION_ID";
console.log("initializing payments...");
const payments = window.Square.payments(appId, locationId);

async function initializeCashAppPay(paymentCount) {
  console.log("initializing Cash App Pay...");
  const paymentRequest = payments.paymentRequest({
    countryCode: "US",
    currencyCode: "USD",
    total: {
      amount: `${paymentCount}.00`,
      label: "Total"
    }
  });
  const cashAppPay = await payments.cashAppPay(paymentRequest, {
    redirectURL: window.location.href,
    referenceId: "my-website-00000001"
  });

  cashAppPay.addEventListener("ontokenization", async function (event) {
    console.log("ontokenization", event);
    // TODO: use event.detail.tokenResult to create a payment

    setTimeout(async () => {
      await cashAppPay.destroy();
      console.log("let's create another payment!");
      initializeCashAppPay(++paymentCount);
    }, 5000);
  });

  console.log("attaching Cash App Pay...");
  await cashAppPay.attach("#cash-app-pay");
}

initializeCashAppPay(1);
```

See it in action: https://codesandbox.io/s/determined-violet-gx2kcl?file=/src/index.js

If you have any other issues, [our Developer Forums](https://developer.squareup.com/forums/tag/web-payments-sdk) is a great place to get help.
