### ISSUE TITLE
Dependency @square/web-payments-sdk-types is out of date

### ISSUE THREAD

**Issue by ntheile** [square/web-sdk#239]
**Is your feature request related to a problem? Please describe.**
The dependency on `@square/web-payments-sdk-types` is out of date, using an old version `v1.1.1` here https://github.com/square/web-sdk/blob/main/package.json#L143 . This version does not include the new types for ACH, specifically the new `AchChargeTokenOptions` required by June 20th (per email from Square)

**Describe the solution you'd like**
I need the npm package updated to use the latest types in `v1.57.0` (or latest version with the type AchChargeTokenOptions) from here https://www.npmjs.com/package/@square/web-payments-sdk-types/v/1.57.0

**Additional context**
I received an email from Square stating that I need to update the ACH payment to add two new parameters to `ach.tokenize()` before June 20, 2024, to continue processing ACH payments:
```
Intent: You must specify your intention to charge the buyer. 
Total: You must specify the amount and currency for the charge.
```
This is also a prerequisite before the square react lib can be updated https://github.com/weareseeed/react-square-web-payments-sdk

**Comment by mhang-square** [comment]
`@square/web-payments-sdk-types` updated to `v1.58.0`
