### ISSUE TITLE
Install Husky with npm install - UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by JohnMAustin78** [square/web-sdk#33]
**Describe the bug**
When running `npm install` to install Husky, I got 

npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.com/npm/-/npm-6.14.11.tgz failed, reason: unable to get local issuer certificate

after I ran `npm config set strict-ssl false`, the previous npm install command worked.

**To Reproduce**

1. run nvm install $(cat .nvmrc)
2. run npm install

**Expected behavior**
The output from `npm install`

> @square/web-sdk@0.0.0 postinstall
> husky install

husky - not a Git repository, skipping hooks installation

added 1359 packages, and audited 1794 packages in 13s

29 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (4 moderate, 3 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 7.19.1 -> 7.20.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.20.3
npm notice Run npm install -g npm@7.20.3 to update!
npm notice 

**Desktop (please complete the following information):**

- OS: [OS X]

**Comment by JHKennedy4** [comment]
This issue has only been reproduced on Square machines, but please let us know if you encounter it in the wild and we'll re-open.
