### ISSUE TITLE
No dist folder in @square/web-payments-sdk-types when installing through NPM

### ISSUE THREAD

**Issue by WinglessFrame** [square/web-sdk#35]
## Descrtiption
No dist folder in @square/web-payments-sdk-types when installing through NPM. When using yarn there is no problem.

## Reproducing
- Using npm(v6), install main square-web-sdk package into project.
- look at node modules:
![image](https://user-images.githubusercontent.com/68775653/129352811-c4d7c5ac-e875-4adf-9f18-78ef5a67f90c.png)
Of course it is failing build as builder cannot resolve import from main square package

### Desktop

- OS: Linux Mint 19 / MacOS

#### Seems like NPM uses latest version (1.8.2) of types lib that is broken
![image](https://user-images.githubusercontent.com/68775653/129355471-404ed1c4-5393-4ce5-9ba5-c4e662343cc8.png)
#### Yarn somehow installs 1.1.2 even though you have newer versions
![image](https://user-images.githubusercontent.com/68775653/129355263-39f90e46-1a86-4746-b1c4-5b37c79ca6ad.png)

**Comment by WinglessFrame** [comment]
BTW is it possible to make this broken lib as dev-dependency inside SDK? I'm using JS in my project so I don't need types for  TypeScript.

**Comment by alexandersmanning** [comment]
Thank you for reporting this. We just fix the issues in [1.8.3](https://www.npmjs.com/package/@square/web-payments-sdk-types/v/1.8.3)
