### ISSUE TITLE
Type expected error when using inside React.js application

### ISSUE THREAD

**Issue by jamilalisgandarov** [square/web-sdk#70]
**Describe the bug**
````
TypeScript error in /Users/${user}/${project}/node_modules/@square/web-payments-sdk-types/dist/types/money.d.ts(13,34):
Type expected.  TS1110

    11 |  * Union of [CurrencyCode](https://developer.squareup.com/reference/sdks/web/payments/enums/CurrencyCode) values.
    12 |  */
  > 13 | declare type CurrencyCodeValue = `${CurrencyCode.GBP}` | string;
       |                                  ^
    14 | /**
    15 |  * Interface for handling any currency
    16 |  * @example
````
**To Reproduce**

1. Go to React application
2. Install '@square/web-payments-sdk-types'
3. Import any type from package (I am trying to use `Card`)
4. Typing error occurs

**Expected behavior**
Can import types without having trouble

**Comment by alexandersmanning** [comment]
It appears something has happened with the '@square/web-payments-sdk-types' package you installed as that code snippet does not match what is in production. You may want to clear out your node_modules and reinstall it. The type should look like:
```typescript
declare type CurrencyCodeValue = `${CurrencyCode}` | string;
```

**Comment by jamilalisgandarov** [comment]
> It appears something has happened with the '@square/web-payments-sdk-types' package you installed as that code snippet does not match what is in production. You may want to clear out your node_modules and reinstall it. The type should look like:
> 
> ```ts
> declare type CurrencyCodeValue = `${CurrencyCode}` | string;
> ```

Oh, sorry I was trying to make changes to see if it helps, actual build is as same as you provided.  But I am still getting the error. I have installed the package through npm and directly tried to use it from the package itself, also tried to add `typeRoots` in tsconfig but it also didn't help.
Type expected - `declare type CurrencyCodeValue = `${CurrencyCode}` | string;`

**Comment by jamilalisgandarov** [comment]
> > It appears something has happened with the '@square/web-payments-sdk-types' package you installed as that code snippet does not match what is in production. You may want to clear out your node_modules and reinstall it. The type should look like:
> > ```ts
> > declare type CurrencyCodeValue = `${CurrencyCode}` | string;
> > ```
> 
> Oh, sorry I was trying to make changes to see if it helps, actual build is as same as you provided. But I am still getting the error. I have installed the package through npm and directly tried to use it from the package itself, also tried to add `typeRoots` in tsconfig but it also didn't help. Type expected - `declare type CurrencyCodeValue = `${CurrencyCode}` | string;`

I was able to make it work after changing all inside package build itself `${Enum} | string` to the `Enum | string`

**Comment by alexandersmanning** [comment]
Interesting, we can look into that.

**Comment by alexandersmanning** [comment]
Aha! We should mention this is TS 4+ 

Thank you for catching this!

**Comment by jamilalisgandarov** [comment]
> Aha! We should mention this is TS 4+
> 
> Thank you for catching this!

I was checking changelog for typescript, looks like Template Literal Types was announced in v4.1 
https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types
