### ISSUE TITLE
Fail to import files when running SSR (nuxt) application

### ISSUE THREAD

**Issue by VividLemon** [square/web-sdk#71]
**Describe the bug**
Seems that in client side, it imports the files just fine, but on server rendering it fails to import
**To Reproduce**
Build nuxt app,
import any from web-sdk
refresh ON PAGE
(Do not client side route to page. Client side routing imports fine!)

**Expected behavior**
Not to error out
**Screenshots**
![image](https://user-images.githubusercontent.com/31498096/153254029-3ff1a851-74f5-448c-b8f7-2369803fa8a3.png)

**Desktop (please complete the following information):**

- OS: [windows 11]
- Browser [Brave]

**Additional context**
Should add notes about the npm package on dev square website. I didn't know it existed before I randomly stumbled on it. Was basically forced to use the CDN as there was no mention of this package on the site.

**Comment by alexandersmanning** [comment]
This is related to: https://github.com/square/web-sdk/pull/67

We are looking for a more longterm fix.

**Comment by kwiksilver3441** [comment]
> This is related to: #67
> 
> We are looking for a more longterm fix.

I believe at the moment nuxt2 only uses webpack 4... Is there any temporary solution I can use besides going back to the CND?

**Comment by maxbeatty** [comment]
Please reopen if v2.0.1 did not fix your issue https://github.com/square/web-sdk/releases/tag/v2.0.1
