### ISSUE TITLE
How to disable postalcode?

### ISSUE THREAD

**Issue by konojunya** [square/web-sdk#92]
How do I disable the ZIP code for credit card payments in Japanese applications?

For example, in-app payments for Android and iOS have documentation like this, but I could not find any description of Web SDK.
ref: https://developer.squareup.com/docs/in-app-payments-sdk/cookbook/disable-postal-code

If it cannot be disabled, the Japanese ZIP code is created from 7 digits. However, only 5 characters can be entered in the payment input field. Therefore, Japanese applications cannot be used to make payments with Square. How can I solve this problem?

![スクリーンショット 2022-04-19 19 18 35](https://user-images.githubusercontent.com/12035578/163983043-089704fa-a582-4d7c-9561-c3303f79ba31.png)

**Comment by JHKennedy4** [comment]
The Card payment method of the Web Payments SDK automatically infers whether to display the postal code and copy (ZIP code, postal code, or postcode) based on the issuing country of the buyer's credit card. Depending on the card that's used, the SDK automatically removes the postal code if the card's issuing country does not require the postal code for the payment.

The test card you are using is considered a US test card, so it requires a postal code, but if you enter a Japanese test card you should see the postal code field disappear.

Definitely reach out if you see a postcode field for a Japanese card, as that should not be the case.
